.github/workflows/ci.yml
docker-compose.yaml
package-lock.json
package.json

Found the culprits:
Closes #15.

chore(CI): fix failing CI Actions

---

src/api/roles.ts
src/api/schemas.ts
src/api/tables.ts
src/api/types.ts
src/lib/constants.ts
src/lib/constants/schemas.ts
src/lib/interfaces.ts
src/lib/sql/roles.sql

- Add `active_connections` and use smarter `connection_limit` in roles.sql
- Exclude default roles by default

refactor: SQL cleanup

---

src/api/tables.ts
src/lib/helpers.ts

Perf tables

---

src/api/columns.ts
src/api/config.ts
src/api/policies.ts
src/api/query.ts
src/api/tables.ts
src/api/types.ts
src/lib/connectionMiddleware.ts

fix: return error responses as JSON objects instead of arrays

---

src/api/columns.ts
src/api/tables.ts
test/integration/index.spec.js

fix: #49 & #50

---

src/api/policies.ts
src/api/query.ts
src/api/tables.ts
test/integration/index.spec.js

Creates test for errors
- Fixes #55

Adds a test for errors

---

package-lock.json
package.json
test/integration/index.spec.js

Bug fix.
pg-format is listed in devDependencies.
pg-format should be listed in dependencies.

fix: pg-format listed in devDependencies

---

.github/workflows/release.yml
.gitignore
Dockerfile
README.md
package.json

Bug fix.
pkg is missing [a dynamic require](https://github.com/datalanche/node-pg-format/blob/3157b520bfec69b05c20f578537c0fe8861f6edf/lib/index.js#L4), so the resulting binaries fail to run.
Add the require to `pkg.scripts` in `package.json`, as per [docs](https://github.com/vercel/pkg#config).

fix: pkg missing a dynamic require in pg-format

---

src/lib/connectionPool.ts

fix: set ssl to false

---

src/lib/connectionPool.ts

fix: setting ssl to false

---

package-lock.json
package.json
src/api/columns.ts
src/api/config.ts
src/api/extensions.ts
src/api/functions.ts
src/api/policies.ts
src/api/publications.ts
src/api/query.ts
src/api/roles.ts
src/api/schemas.ts
src/api/tables.ts
src/api/types.ts
src/lib/connectionMiddleware.ts
src/lib/connectionPool.ts
src/lib/logger.ts
src/server.ts

Feature.
Logging is done with `console.log`s
Improve logging with [pino](https://github.com/pinojs/pino). Among other things that get logged:
- Log levels (`info`: `30`, `error`: `50`)
- Postgres connection string
- Request body
Closes #83.

feat: improve logging with pino

---

src/api/columns.ts
src/api/policies.ts
src/api/publications.ts
src/api/tables.ts
src/lib/helpers.ts
src/server.ts

Bug fix, feature, docs update, ...

refactor: add some small changes

---

.pkg.config.json
package.json

Bug fix.
SQL templates aren't included in the `pkg`'d bins.
Include the SQL templates.
Closes #95.

fix(release): include sql assets

---

src/lib/PostgresMetaTriggers.ts
src/lib/sql/triggers.sql

chore(triggers): clean up PostgresMetaTriggers and triggers sql

---

src/lib/PostgresMetaFunctions.ts
src/lib/sql/functions.sql
src/lib/types.ts
test/integration/index.spec.js

feature
Enable function definition update.

feat: enable function definition update

---

src/lib/PostgresMetaColumns.ts

https://support.supabase.org/a/tickets/3305

fix(lib/columns): identity_generation default value

---

README.md

Can't rerun the docker job due to `if: needs.semantic-release.outputs.new-release-published == 'true'`: https://github.com/supabase/postgres-meta/blob/ea1c5537dd10b9f3f6c87906da01a3b5a039ecd4/.github/workflows/release.yml#L68, so making a trivial commit.

Add periods to numbered list

---

package-lock.json
package.json
src/lib/PostgresMetaPublications.ts
src/lib/db.ts
src/server/app.ts
src/server/routes/columns.ts
src/server/routes/config.ts
src/server/routes/extensions.ts
src/server/routes/functions.ts
src/server/routes/policies.ts
src/server/routes/publications.ts
src/server/routes/query.ts
src/server/routes/roles.ts
src/server/routes/schemas.ts
src/server/routes/tables.ts
src/server/routes/triggers.ts
src/server/routes/types.ts
src/server/utils.ts
test/lib/config.ts

Had to dig through pg-meta logs through CloudWatch and it was next to useless. This improves the log output by:
- reverting to log error, request, etc. as JSON instead of stringified JSON (from https://github.com/supabase/postgres-meta/pull/149)
- logs the db hostname the query is run against
@darora let me know if this is violating personal info thingy or if there's any extra stuff you want logged!

fix: improve logging

---

package-lock.json
package.json
src/server/app.ts
src/server/routes/index.ts
src/server/routes/query.ts
src/server/utils.ts

Both server & client side logs are provided where applicable.
- if query is not provided
Before (think the server also crashes?):
```
TypeError: Client was passed a null or undefined query
at Client.query (/Users/darora/src/supabase/postgres-meta/node_modules/pg/lib/client.js:505:13)
[...]
[ERROR] 08:01:52 TypeError: Client was passed a null or undefined query
```
```
* Empty reply from server
* Closing connection 0
curl: (52) Empty reply from server
```
After:
```
{"level":"error","time":"2022-01-18T00:06:44.730Z","pid":77960,"hostname":"Divs-MacBook-Pro.local","error":"Error: query not found","request":{"method":"POST","url":"/query","pg":"localhost"}}
```
```
< HTTP/1.1 500 Internal Server Error
< 
* Connection #0 to host localhost left intact{"error":"query not found"}%      
``` …

Better error messages

---

src/server/app.ts
src/server/constants.ts

retains the default, but allows us to override it

feat: customizable request header name

---

.github/dependabot.yml
package-lock.json
package.json

- new pgsql-parser uses pre-built binaries when possible

Upgrade dependencies and enable dependabot

---

Dockerfile

Fixes issue with requests returning a 404 not found

fix: Revert "Use alpine node image for Dockerfile"

---

src/lib/sql/policies.sql
src/lib/sql/schemas.sql

Bug Fix
[Please link any relevant issues here.
](https://github.com/supabase/postgres-meta/issues/212)
Change the use of pg_authid to pg_roles

feat: change pg_authid 2 pg_roles

---

.github/workflows/release.yml
src/server/app.ts

Bug fix
typo in error
also updates GHA to publish to ECR mirror

fix: error message logging when run from cli

---

src/server/constants.ts

fix: escape db password

---

src/server/templates/typescript.ts

Context: https://github.com/supabase/cli/issues/413

fix(typegen): enum arrays

---

src/server/templates/typescript.ts

Context: https://github.com/supabase/cli/issues/388
Now it looks like:
```
[...]
Functions: {
add:
| {
Args: Record<string, unknown>;
Returns: number;
}
| {
Args: Record<PropertyKey, never>;
Returns: undefined;
};
};
[...]
```

fix(typegen): function overloading

---

src/server/templates/typescript.ts

Context: https://github.com/supabase/cli/issues/422

feat(typegen): enums

---

src/lib/sql/columns.sql
test/lib/columns.ts

Context: https://github.com/supabase/supabase/pull/9223
cc @joshenlim

feat(columns): populate enums in enum array columns

---

src/server/templates/typescript.ts

E.g.
```sql
-- unnamed OUT parameter
create function f(OUT text) returns void as $$ $$ language sql;
```
Shows up as
```ts
export type Json =
| string
| number
| boolean
| null
| { [key: string]: Json }
| Json[];
export interface Database {
extensions: {
Functions: {
f: {
Args: { OUT: text };
Returns: undefined;
};
};
};
}
```

fix(typegen): malformed function args

---

src/lib/PostgresMetaRoles.ts
src/lib/types.ts
test/lib/roles.ts

Feat
Added the option to set Config at creation time, which we can now use to manage the Config of the Role, such as search_path
We can set role when create.

feat: add config support for role

---

src/lib/PostgresMetaRoles.ts
src/lib/types.ts
src/server/routes/roles.ts

Chore
No type for update and create role.
Add Type for update and create role.

chore: add role schema

---

src/server/templates/typescript.ts

Context: https://github.com/supabase/cli/issues/577

fix(typegen): respect nullability in view columns

---

.github/workflows/ci.yml
package-lock.json
package.json
src/server/app.ts
src/server/routes/columns.ts
src/server/routes/extensions.ts
src/server/routes/functions.ts
src/server/routes/index.ts
src/server/routes/policies.ts
src/server/routes/publications.ts
src/server/routes/tables.ts
src/server/routes/triggers.ts

- fixes #397
- adds typecheck to CI tests
- updates deps
- fixes HTTP router hacks that no longer works after updating deps

fix: type errors and router hacks

---

src/lib/PostgresMetaTypes.ts
src/lib/sql/types.sql
src/server/app.ts
src/server/routes/generators/typescript.ts
src/server/routes/types.ts
src/server/templates/typescript.ts

addresses https://github.com/supabase/cli/issues/635, https://github.com/supabase/supabase/discussions/10464

fix(typegen): function with table return type

---

.github/workflows/mirror.yml
.github/workflows/release.yml

Bug fix, feature, docs update, ...

chore: add ghcr image mirror

---

src/lib/PostgresMetaTriggers.ts

fix(triggers): allow include/exclude schema(s)

---

.github/workflows/mirror.yml
.github/workflows/release.yml

instead of long lived access keys

fix: switch to using aws role

---

.github/workflows/release.yml

Fixes https://github.com/supabase/postgres-meta/actions/runs/3899494536/jobs/6659197217

fix: CI permissions

---

.github/workflows/ci.yml

Feature. Build, run and healthcheck with Docker every push or PR.
Improves catching early bugs.
No issue

CI: add Github Action to build with Docker

---

package-lock.json
package.json
src/lib/PostgresMetaTables.ts
src/lib/types.ts
src/server/routes/foreign-tables.ts
src/server/routes/schemas.ts
src/server/routes/tables.ts
src/server/routes/views.ts

Removes duplication of JSON schema + TypeScript types.

chore(deps): use @fastify/type-provider-typebox

---

src/server/templates/typescript.ts

Bug fix
[Current behavior - issue #478 ](https://github.com/supabase/postgres-meta/issues/478)
line 310
```return `${JSON.stringify(name)}: unknown` ```

fix: return field name with composite type unknown

---

package.json

From https://github.com/supabase/postgres-meta/pull/481

fix: wrong `types` file

---

src/lib/PostgresMetaColumns.ts
src/lib/sql/columns.sql
test/lib/columns.ts
test/lib/foreign-tables.ts
test/lib/tables.ts
test/lib/views.ts

feature
Users can create check constraints.
Users can also view and update check constraints in addition to creating them.

feat: view and update check constraints

---

.releaserc.json

This should make it less likely to hit GH API rate limits

fix: semantic-release job

---

src/lib/PostgresMetaColumns.ts

Bug fix
You get an error if you send `null` in the `check` field when updating a column.
Can delete `check` constraints as expected.

fix: allow deletion of check constraints

---

.releaserc.json

GitHub rate limit, go pound sand

fix: rate limit strikes back

---

src/server/constants.ts
test/server/query.ts

Reverts supabase/postgres-meta#768

Revert "fix: query timeout"

---

src/server/templates/typescript.ts
test/server/typegen.ts

Fixes https://github.com/supabase/postgres-meta/issues/810

fix(typegen): view relationships ordering

---

src/lib/sql/table_privileges.sql
src/lib/types.ts

[Context](https://supabase.slack.com/archives/C06RHDLTT3J/p1733122256726169)

feat: support `MAINTAIN` privilege in PG17

---

.github/workflows/ci.yml
package-lock.json
package.json
vitest.config.ts

https://coveralls.io/jobs/159843438

chore: upload coverage to coveralls

---

src/server/constants.ts

This will help our support team debug lots of various issues.

ref: Add 'postgres-meta <version>' application_name to defaults

---

.github/workflows/release.yml

Deploy already!! https://github.com/supabase/postgres-meta/actions/runs/14194095900

chore: CD perms

---

README.md

remove sponsorship ask

---

src/server/templates/typescript.ts

Fixes #959 
See: https://github.com/supabase/postgres-meta/issues/959#issuecomment-3145665493

fix(typegen): ensure determinism in functions returns properties
