.github/workflows/ci.yml
.github/workflows/release.yml

Automates testing, building, releasing binary and deploying to fly.io up tag push. (Needs a secret: FLY_API_TOKEN)
I tried finding a release notes generator, but couldn't find one that "works" (generate changelog into Releases body upon tag push). Candidates were:
- [Release Drafter](https://github.com/release-drafter/release-drafter)
It can generate drafts of changelog upon push to branches, but it can't handle tag pushes
- [github-changelog-generator](https://github.com/github-changelog-generator/github-changelog-generator) or [zeit/release](https://github.com/zeit/release)
Looks good, but they're manually triggered (not GitHub Actions)
- [release-notary](https://github.com/aevea/release-notary)
This one seems to do exactly what I want, but it errors out and gives undecipherable error …

Add GH Actions workflows

---

src/api/columns.ts
src/api/functions.ts
src/api/roles.ts
src/api/schemas.ts
src/api/tables.ts
src/api/types.ts
test/integration/index.spec.js

Request parameters are of the type ParsedQs (see @types/qs). Here's the
type definition:
interface ParsedQs { [key: string]: undefined | string | string[] | ParsedQs | ParsedQs[] }
Note that the params aren't converted to JS types by default.
Currently, these query params are casted to an interface with boolean
values, but TypeScript doesn't convert these string params at
runtime (rather, TypeScript is only useful on compile time), so a
`string` is used where a `boolean` is expected.
To reproduce the error, uncomment the test labelled with FIXME.

fix: request query parameter handling

---

src/api/columns.ts
src/api/tables.ts
test/integration/index.spec.js

Covers /tables & /columns on PATCH.
Closes #44.

fix: don't run name-change SQL when unchanged

---

docs/api.yml
docs/index.html
docs/package-lock.json
docs/package.json
docs/source/index.html.md

This adds the initial OpenAPI spec for pg-api.
Most of the skeleton is in place, but it's still missing some things, e.g.:
- Non-boiletplate examples
- Failing HTTP responses
- Descriptions
- Test against an OpenAPI validator
- Verify required/nullable fields against actual properties on Postgres
I don't think we can get this right the first time, so let's go with this and Kaizen the rest.
Also, this spec slightly differs from the current implementation (camelCase vs. snake_case, type inconsistencies). These will be addressed in the future.
P.S. To view the docs, run `npm run dev:watch` in the `docs` directory.

docs(openapi): add initial OpenAPI spec

---

package-lock.json
package.json
src/api/columns.ts
src/api/extensions.ts
src/api/policies.ts
src/api/roles.ts
src/api/schemas.ts
src/api/tables.ts
test/integration/index.spec.js
tsconfig.json

Bug fix
Closes #57.
pg-format is now used in most places, so using `'` in `COMMENT`s should work.

fix: Improve escaping of identifiers and SQL literals

---

src/lib/sql/columns.sql
src/lib/sql/grants.sql
src/lib/sql/policies.sql
src/lib/sql/primary_keys.sql

Bug fix
Closes #39. Closes #56.
Apparently Postgres converts oid to string when converting to JSON, so we have to explicitly cast table_id columns for `columns`, `grants`, `policies`, and `primary_keys` to type int8.

fix: table_id types mismatch

---

package.json
src/api/tables.ts
src/lib/connectionPool.ts
src/lib/interfaces.ts
src/lib/sql/tables.sql
test/integration/index.spec.js

Feature.
Add `replica_identity` to `/tables`. This allows e.g. setting `REPLICA IDENTITY` to `FULL` like so:
```sh
curl -X PATCH http://localhost:1337/tables/16391 -H "Content-Type: application/json" -d '{ "replica_identity": "FULL" }'
```
Together with #67, closes #65.

Add replica identity fields to /tables

---

src/api/columns.ts
src/api/config.ts
src/api/extensions.ts
src/api/functions.ts
src/api/policies.ts
src/api/roles.ts
src/api/schemas.ts
src/api/tables.ts
src/api/types.ts

Bug fix.
Most error responses are `500 Server Error` with error message `Database error.`, which is not very helpful.
Error handling goes like this:
- Baseline response on error is 400 Bad Request, propagating Postgres's error message
- If the request is infallible (e.g. GET with no payload/query params), respond with 500 Server Error, again propagating Postgres's error message
- More specific responses can be done as more specific errors are found (404 for missing IDs, etc.)

fix: propagate errors from Postgres

---

src/api/columns.ts

Bug fix.
Missing default value for `identity_generation` in `POST /columns`. This makes requests to add columns fail when `is_identity` is `true` but `identity_generation` is unset.
`identity_generation` is set to `BY DEFAULT`. This is the previous behavior before support for `identity_generation` was added.

fix(columns): identity_generation missing default

---

src/api/columns.ts
test/integration/index.spec.js

Bug fix.
Previously supplying e.g. `int4[]` as column type would error out because the brackets are treated as part of the type name (as opposed to denoting that it's an array of `int4`s).
Remove the quoting around `data_type`s so we can supply `foo[]` instead of `_foo`.
cc @joshenlim

fix: allow array column type

---

src/lib/sql/extensions.sql

Feature.
Add `schema` field to `/extensions`. Note that an extension doesn't belong to a schema, only an extension's objects do ([ref](https://www.postgresql.org/docs/current/catalog-pg-extension.html)).

feat: add schema to /extensions

---

src/lib/sql/tables.sql

Bug fix.
Rename row count estimates from the statistics collector.
Closes #66.
As I mentioned in #66, we should be explicit that these numbers are estimates.
P.S. this doesn't exactly solve the problem in #66, that one needs either exact count (bad for large tables) or `ANALYZE` (but it's [automatically run](https://www.postgresql.org/docs/12/runtime-config-autovacuum.html#GUC-AUTOVACUUM-ANALYZE-THRESHOLD) for large inserts/updates/deletes by default anyway--but the user will have to wait). So... wontfix?

Rename row count estimates

---

src/lib/sql/functions.sql
src/lib/sql/policies.sql
src/lib/sql/publications.sql
src/lib/sql/roles.sql
src/lib/sql/types.sql

Bug fix.
Some SQL templates use `oid`, which is converted to `string` by node-postgres.
Convert them to `int8`.

fix: convert oids to int8

---

docker-compose.yaml
src/api/columns.ts
test/integration/index.spec.js

Bug fix.
Changing default value and type at once changes the default value *first*, i.e. for the old type, which is not what we want.
Change the type first.

fix: error when changing type & default at once

---

README.md

docs update
Broken link to documentation

fix: broken documentation URL

---

src/lib/sql/publications.sql

Bug fix.
`/publications`'s tables only have names, so we can't differentiate tables from different schemas.
Make `tables` a JSON object as per #97. (Breaking change)
Closes #97.

fix(publications): disambiguate tables' schemas

---

package-lock.json
package.json
src/server/app.ts
src/server/logger.ts
src/server/routes/columns.ts
src/server/routes/config.ts
src/server/routes/extensions.ts
src/server/routes/functions.ts
src/server/routes/index.ts
src/server/routes/policies.ts
src/server/routes/publications.ts
src/server/routes/query.ts
src/server/routes/roles.ts
src/server/routes/schemas.ts
src/server/routes/tables.ts
src/server/routes/types.ts

Feature.
Use Fastify for the server in place of Express.
There's no logic change, but it's still a big change in terms of LoC, no way around it since code organization is different under Fastify (can't just `s/express/fastify`).
Some next steps (post-March):
- Request & response validation (currently types from request, minus `body`, are checked at compile time--during runtime all bets are off). Will need to export types from the lib.
- Split up tests, it's getting hairy... Maybe use jest?

Use Fastify in place of Express

---

test/integration/index.spec.js

Noticed that there weren't tests for `is_primary_key`, added one. If this approach looks good, I'll try to figure out how to add one for the unique constraint as well.

test: Add test for creating primary_key column

---

src/lib/PostgresMetaPublications.ts
test/integration/index.spec.js

Bug fix.
In `/publications` POST & PATCH, table names with uppercase aren't escaped properly.
Handle it properly.
Fixes #106.

fix(publications): handle table name w/ uppercase

---

test/integration/index.spec.js

Adds a test for `is_unique`. Follow-up to #105.

test: Add test for is_unique columns

---

src/lib/PostgresMetaColumns.ts
test/integration/index.spec.js

Allows users to define a `constraint` when creating a column https://github.com/supabase/postgres-meta/issues/100. Technically a user could specify multiple constraints in the string, not sure if we'd want something more structured? e.g. an array.

feat(lib): add naive constraint definition

---

.github/workflows/docs.yml
.gitignore
docker-compose.yaml
package-lock.json
package.json
src/lib/PostgresMetaSchemas.ts
src/lib/types.ts
src/server/app.ts
src/server/constants.ts
src/server/routes/schemas.ts
test/integration/index.spec.js

Feature.
Adds preliminary code for generating OpenAPI spec.
- Uses [TypeBox](https://github.com/sinclairzx81/typebox) to generate both JSON Schema & TypeScript types in one go—pretty handy!
- Uses fastify-swagger to generate OAS (like in storage-api)
- Preliminary support is for `/schemas` route only (all verbs)
- Includes types for POST and PATCH so no need to chase postgres-meta source code function calls anymore :-)
- Exporting docs is done by setting `PG_META_EXPORT_DOCS` to `true` (server doesn't start up with this option, this is for exporting docs only)
- Publishes docs to `gh-pages` branch - @kiwicopple might need to change the GitHub Pages settings
Currently it exports openapi.json with the following contents:
<details>
```json
{
"openapi": "3.0.3",
"info": {
"title": …
```

feat: Add preliminary code for generating OAS

---

src/lib/PostgresMetaFunctions.ts
src/server/routes/functions.ts
test/integration/index.spec.js

functions list action is already implemented, adding the remaining actions (get, post, patch,
delete). Beginning with this test for GET on /functions/:id
list method already implemented, missing get, post, patch & delete
#115 
Please pardon my linter's overzealous linting 🙈

[WIP] feat(/functions): add remaining functions routes

---

src/lib/PostgresMetaPublications.ts

Bug fix
Related issue: https://github.com/supabase/supabase/issues/2123
Getting error: `"relation \"public.test\" does not exist"` (example error) b/c of the double quotes.
Double quotes are removed and I'm able to create/update publications

Fix: remove double quotes from publications create and update

---

src/lib/PostgresMetaFunctions.ts
src/lib/PostgresMetaTriggers.ts
src/lib/sql/triggers.sql
test/integration/index.spec.js

Bug fix
retrieve function returns multiple records due to overloaded function names.
retrieve function returns single record despite overloaded function names.
@i-pip creating this PR as it was out of scope for https://github.com/supabase/postgres-meta/pull/118.

fix(functions): include argument_types retrieving function query

---

src/lib/index.ts

This PR will allow types defined in `src/lib/types.ts` to be exported. It addresses issue #126.
No types are currently exported.
Types will be exported.

Export types

---

src/lib/PostgresMetaFunctions.ts
src/lib/sql/functions.sql
src/lib/types.ts
test/integration/index.spec.js

feature
Add the following options when creating functions:

feat: add additional function create options

---

src/lib/PostgresMetaFunctions.ts
test/integration/index.spec.js

chore
function create `rettype` option
function create `return_type` option
Related issue: https://github.com/supabase/postgres-meta/issues/132

chore: update function option rettype to return_type

---

src/lib/PostgresMetaTriggers.ts
src/lib/sql/triggers.sql
src/lib/types.ts
test/integration/index.spec.js

feature
add tg_rel_id (trigger table id) in trigger return

feat: add table_id to trigger return

---

src/lib/PostgresMetaFunctions.ts
src/lib/sql/functions.sql
src/lib/types.ts
test/integration/index.spec.js

feature
when creating a function, `config_params` is passed in as object where both param and value are strings.

feat: change function config param value to string

---

src/lib/PostgresMetaFunctions.ts
test/integration/index.spec.js

Bug fix
create function, but fails to fetch created function, with function args being alias data types like `int2, int4, etc.`
create function, then successfully fetch created function, with function args being alias data types like `int2, int4, etc.`
test example:
```
{
"name":"add",
"schema":"public",
"definition":"SELECT a + b;",
"rettype":"integer",
"language":"sql",
"behavior":"STABLE",
"args":["a int4","b int4"]
}
```

fix: create functions with alias data types

---

package-lock.json
package.json
src/lib/PostgresMetaFunctions.ts
src/lib/types.ts

refactor
Creating and updating functions will use the `PostgresFunctionCreate` type.
Refactor based on feedback: https://github.com/supabase/postgres-meta/pull/137#issuecomment-886453986

refactor: convert FunctionInputs to PostgresFunctionCreate

---

.github/workflows/ci.yml
.github/workflows/docs.yml
.github/workflows/release.yml
package-lock.json
package.json
src/server/constants.ts
src/server/routes/columns.ts
src/server/routes/config.ts
src/server/routes/extensions.ts
src/server/routes/functions.ts
src/server/routes/policies.ts
src/server/routes/publications.ts
src/server/routes/query.ts
src/server/routes/roles.ts
src/server/routes/schemas.ts
src/server/routes/tables.ts
src/server/routes/triggers.ts
src/server/routes/types.ts

Remember to update PR to resolve [pg v8 breaking change](https://node-postgres.com/announcements#support-all-tlsconnect-options-being-passed-to-the-clientpool-constructor-under-the-ssl-option).
deps version bumps
pg v7 and node v12
pg v8 and node v14
related issue: https://github.com/supabase/postgres-meta/issues/121

chore(deps): bump pg to v8.6.0 and node to v14

---

package.json
src/server/routes/columns.ts
src/server/routes/schemas.ts
src/server/routes/tables.ts
src/server/routes/triggers.ts

Bug fix.
Some failing requests are returning cryptic `Cannot read property 'accept-version' of undefined` error.
Sayonara cryptic errors. Responses should now provide the *actual* errors.
Closes #144.
Related: https://github.com/supabase/supabase/issues/2404#issuecomment-913153702

fix(server): Cannot read property 'accept-version' of undefined

---

README.md
src/lib/PostgresMetaFunctions.ts

Bug fix
Attempting to select existing function returns all functions with the same identity_argument_types.
Selecting existing function returns a single function based on its schema, name, and identity_argument_types.
Related issue:  https://github.com/supabase/supabase/issues/3281

fix: update existing function query

---

src/lib/PostgresMetaRoles.ts
src/lib/PostgresMetaTables.ts
src/lib/helpers.ts

This SQL adapted from pg-meta doesn't do what it says on the tin:
```postgresql
WITH tables AS (
SELECT
c.oid :: int8 AS id,
c.relname AS name,
c.relnamespace :: regnamespace :: text AS schema
FROM
pg_class c
WHERE
c.relkind = 'r'
),
policies AS (
SELECT
pol.oid :: int8 AS id,
pol.polname AS name,
c.oid :: int8 AS table_id
FROM
pg_policy pol
JOIN pg_class c ON c.oid = pol.polrelid
)
SELECT
*,
COALESCE(
(
SELECT
array_to_json(array_agg(row_to_json(policies)))
FROM
(
SELECT
*
FROM
policies
WHERE
policies.table_id = tables.id
) policies
),
'[]'
) AS policies
FROM
tables
WHERE
tables.schema = 'public';
```
Instead you need to do:
```postgresql
WITH tables AS (
SELECT
c.oid :: int8 AS id,
c.relname AS name,
c.relnamespace :: regnamespace :: text AS schema
FROM
pg_class c
WHERE
c.relkind = 'r' …
```

fix: obscure policies CTE bug

---

src/lib/PostgresMetaTables.ts
test/lib/tables.ts

Fixes https://github.com/supabase/postgres-meta/issues/145.
Example:
```js
await pgMeta.tables.update(id, {
primary_keys: [{ name: 'col1' }, { name: 'col2' }],
})
```

feat(lib/tables): support setting primary keys

---

package-lock.json
package.json
src/server/app.ts

- emit a string level rather than numeric (i.e. 'error' instead of 50)
- emit a readable ISO8601 timestamp instead of unix epoch time
Before:
```
{"level":30,"time":1642458666771,"pid":29532,"hostname":"Divs-MacBook-Pro.local","msg":"App started on port 1337"}                   
```
After:
```
{"level":"info","time":"2022-01-17T23:03:27.847Z","pid":78485,"hostname":"Divs-MacBook-Pro.local","msg":"App started on port 1337"}
```

chore: cleaner logging output

---

src/server/constants.ts

By default there is no timeout, which results in fairly unhelpful
messages from other components in the stack because they do have
limits of e.g. 60s

feat: default connection timeout of 15 seconds

---

src/server/routes/query.ts
src/server/routes/tables.ts
src/server/utils.ts

When we terminate an upstream connection due to a timeout, we ought to
respond with a 504 rather than a 400.

fix: respond with a 504 if appropriate

---

src/server/utils.ts

the pg header is insufficient for loads of debugging scenarios.

feat: additional header for debugging information

---

src/lib/PostgresMetaColumns.ts
test/lib/columns.ts

Fix [issue 5330](https://github.com/supabase/supabase/issues/5330) of Supabase Upstream. 
Updating column data type from `type` to `type[]`  fails because of insufficient identifier escaping in colum `create` and `update` function.
This is actually a TO-DO  so it's safe to delete the Todo comment now :).

fix: handling of type identifier in column create() and update()

---

package-lock.json
package.json
src/lib/db.ts
test/lib/roles.ts

Fixes https://github.com/supabase/postgres-meta/issues/174.
dates, timestamps, and timestamptzs are no longer converted to JS Dates.
date before: "2020-01-01T00:00:00.000Z"
date after: "2020-01-01"

fix: date & timestamp format

---

Dockerfile

This reverts commit 26a99800b1dbddd76486f4967a3868327e3dc2c3.

fix: Revert "chore: use slim node base image"

---

src/server/constants.ts

Allows end user to optionally enable SSL mode on db connections 
Currently the behavior is to disallow all SSL connections and not provide end user the option to allow them
New behavior is to default to disallow SSL connections but allow end user to allow them via environment variable
While this app is, as the readme states, intended to run in an unexposed environment, there are still valid use cases for having SSL enabled in these kinds of environments.

feat: allow end user to turn on ssl mode for db connections

---

src/lib/PostgresMetaColumns.ts
src/lib/PostgresMetaTables.ts
src/lib/types.ts
src/server/routes/columns.ts
test/lib/columns.ts
test/lib/tables.ts

Listing columns from a single table is done like `GET /columns/:tableId`.

feat(lib): omit policies from /tables and allow listing columns from a single table

---

src/server/routes/generators/typescript.ts
src/server/routes/index.ts
src/server/templates/typescript.ts

e.g. for current test fixtures:
https://github.com/supabase/postgres-meta/blob/38c325f6eb81fe82806d5c17f4e288df3bc5be8c/test/db/00-init.sql#L1-L53
https://github.com/supabase/postgres-meta/blob/38c325f6eb81fe82806d5c17f4e288df3bc5be8c/test/db/01-memes.sql#L1-L34
Generated types:
```ts
export type Json =
| string
| number
| boolean
| null
| { [key: string]: Json }
| Json[];
export interface Database {
public: {
Tables: {
users: {
Row: {
id: number;
name: string | null;
status: "ACTIVE" | "INACTIVE" | null;
};
Insert: {
id?: number;
name?: string | null;
status?: "ACTIVE" | "INACTIVE" | null;
};
Update: {
id?: number;
name?: string | null;
status?: "ACTIVE" | "INACTIVE" | null;
};
};
todos: {
Row: {
id: number;
details: string | null;
"user-id": number;
};
Insert: {
id?: number;
details?: …
```

feat: add typescript typegen endpoint

---

src/lib/db.ts
test/lib/query.ts

Because JS only has float64 numbers.
Pretty hacky solution right now - in the future we should always parse `int8` as `string`.

fix(lib): parse int8 as string

---

package-lock.json
package.json
src/server/admin-app.ts
src/server/app.ts

The first endpoint included is for metrics using the prometheus
exposition format.

feat: add a secondary port with admin endpoints

---

README.md
src/server/app.ts
src/server/constants.ts

Non breaking change that adds an environment variable to control fastify host. This unlocks connections using IPv6 connections by setting `PG_META_HOST` as `::`.
Current configuration only allows IPv4 port binding. See https://www.fastify.io/docs/latest/Reference/Server/#listen
Configuration can be set to support IPv6 binding.

feat: support IPv6 address binding

---

src/lib/sql/functions.sql
src/lib/types.ts
test/lib/functions.ts

Right now we have `argument_types`, but it's not very useful with its current format of a string.
The new `args` property has the format
```ts
{
mode: 'in' | 'out' | 'inout' | 'variadic' | 'table'
name: string
type_id: number
}[]
```
which is easier to consume.

feat(functions): add `args` property

---

src/lib/PostgresMetaPublications.ts
src/lib/db.ts
src/lib/sql/publications.sql
test/lib/publications.ts

feature
Updating a publication from list of tables to all tables (and vice versa) gives 400
Support updating a publication from list of tables to all tables and vice versa
https://www.notion.so/supabase/Ensure-pg-meta-update-publication-works-for-all-and-subset-of-tables-163ef66392eb490c981df4c276cd577b

fix(publications): support list of tables <-> all tables on update

---

src/lib/PostgresMetaPublications.ts

Bug fix
When there is an error on `PATCH /publications`, the actual error is hidden by `data[0]` where `data` is `null`. The error returned becomes:
```
Cannot read properties of null (reading '0')
```
The error becomes the actual error, e.g.:
```
must be owner of publication supabase_realtime
```

fix(lib/publications): check error before indexing array

---

src/server/templates/typescript.ts

As reported in this issue https://github.com/supabase/cli/issues/602
Quite a few users are having issues with generated types randomly changing making it hard to integrate in a CI.
Only tables and views are sorted, not the columns.
Hopefully columns would be sorted too although I am not sure how to test this! 😁

fix: always sort the table & view columns

---

src/lib/PostgresMetaTables.ts
src/server/routes/tables.ts
test/lib/tables.ts

feature https://www.notion.so/supabase/pg-meta-tables-support-fetching-tables-from-a-specified-schema-6ac33f9b73a542158f0a31bf25399bd7
all schemas are included when listing tables
supporting listing tables of specific schemas

fix: support schemas query param for listing tables

---

Dockerfile
jest.config.js
package.json
tsconfig.json
tsconfig.module.json
tsconfig.server.json

build
commonjs
no need to support commonjs as pg-meta is purely server side

chore: switch build to esnext module type

---

src/server/templates/typescript.ts

Feature
When generating TypeScript types (`supabase gen types typescript`), columns with `citext` (case insensitive text) data type show up as `unknown`.
Columns with `citext` data type will now show up as `string`.
Added `citext` to list of types that will generate a `string` TypeScript type. Also confirmed that [this query](https://github.com/supabase/postgres-meta/blob/42d3ea7910358d57be365355632195a7c50199d4/src/lib/sql/columns.sql#L28) does in fact output `citext` under `format` when the column has `citext` data type as is referenced [here](https://github.com/supabase/postgres-meta/blob/42d3ea7910358d57be365355632195a7c50199d4/src/server/templates/typescript.ts#L77).

feat: support citext data type when generating typescript types

---

src/lib/sql/types.sql
src/lib/types.ts
src/server/templates/typescript.ts
test/lib/types.ts

feature
Attributes of [composite types](https://www.postgresql.org/docs/current/rowtypes.html) are not returned
Add an `attributes` field for composite types. Also add `CompositeTypes` for each schema in the generated types.
Closes #399

feat: composite type attributes

---

Dockerfile

Feature. Add `HEALTHCHECK` to `Dockerfile`
1. There is `/health` endpoint
2. Why not?
No issue
Set interval and timeout to 5 seconds, is it ok?

Add HEALTHCHECK to Dockerfile

---

package.json

Bug fix.
Types are not exported by default so adding `types` field to package.json.
Resolves this issue: https://github.com/supabase/supabase/actions/runs/3980851540/jobs/6824193248
Tested locally by manually adding this field in node_modules, works.

fix: add "types" field to package.json

---

README.md
src/server/templates/typescript.ts

Makes all table function column return types nullable.
The verbatim function types are used as column types despite the functions potentially returning `null`.
All return types are treated as nullable.
@psteinroe contributed a change which adds schema functions which take only the table name as columns on the tables when generating TypeScript types.
This commit extends that to treat function return types as nullable.
The function used in `oo-init.sql` could be changed like so:
```sql
create function public.blurb(public.todos) returns text as
$$
select null;
$$ language sql stable;
```
It would still compile and be a valid function despite the unchanged return type, which means any function must be treated as potentially returning `null` in the types.
I have also updated instructions for …

Make function return types nullable

---

src/lib/PostgresMetaRoles.ts
src/lib/constants.ts
test/lib/roles.ts

Bug fix.
Fixes logic with `includeDefaultRoles`. Actually a breaking change.
Maybe I should change `includeDefaultRoles` to `true` to not change the behavior?

fix: Fix logic when returning default roles

---

README.md
src/lib/sql/types.sql

`pg_attribute` may contain records for attributes that were dropped but Postgres kept them around and instead of deleting them, renamed them to `........pg.dropped.#........` and set their `attisdropped` to `true`.
This ends up generating these dropped attributes as `unknown` fields in the TypeScript types.
In this commit I updated the `types` query to not return these.
Maybe it would be preferrable to instead keep these but skip them only when generating the TypeScript types?
Feature? Maybe bug fix?
It is arguable whether these dropped attributes should appear in the generated types and be accessible via the Postgres Meta API. I expect folks might lean towards exposing them instead of skipping them. In this case I'd like to contribute a change which adds a new `dropped` boolean field on …

Skip over dropped attributes when enumerating types

---

.github/workflows/publish-deps.yml
Dockerfile

build and publish binary deps
binaries are built locally
add GHA workflow for auto publishing

chore: add workflow to publish binary dependencies

---

src/server/templates/typescript.ts

Adds pgvector's `vector` data type to TypeScript generation logic to produce a ~~`number[]`~~ `string` type.
Edit: `vector` actually produces a `string`, eg `"[1,2,3]"`.

feat: support vector data type when generating typescript types

---

src/lib/PostgresMeta.ts
src/lib/PostgresMetaRelationships.ts
src/lib/PostgresMetaTables.ts
src/lib/sql/index.ts
src/lib/sql/relationships.sql
src/lib/sql/relationships_old.sql
src/lib/types.ts
src/server/routes/generators/typescript.ts
src/server/server.ts
src/server/templates/typescript.ts
test/server/typegen.ts

Include table relationships in typegen. This is a prerequisite for determining the cardinality of a relationship, which is necessary to resolve https://github.com/supabase/postgrest-js/issues/303.
An example is shown in the diff for test/server/typegen.ts.

feat(typegen): table relationships

---

src/server/routes/generators/typescript.ts
src/server/server.ts
src/server/templates/typescript.ts

Or views etc. This can be expensive on a complex enough schema and can easily trip over the 15s timeout.
Instead, query all columns separately, which should hopefully be less taxing and easier to plan.
Also omit excluded schemas when listing tables/views/etc.
Benchmark results on 100 tables with 100 columns each:
Before:
```
Time (mean ± σ):      8.134 s ±  0.211 s    [User: 0.094 s, System: 0.017 s]
Range (min … max):    7.857 s …  8.569 s    10 runs
```
After:
```
Time (mean ± σ):      1.787 s ±  0.113 s    [User: 0.094 s, System: 0.016 s]
Range (min … max):    1.648 s …  1.980 s    10 runs
```

fix(typegen): omit `columns` when querying tables

---

src/server/templates/typescript.ts
test/server/typegen.ts

See also https://github.com/denoland/deno_std/pull/2565. Omitting `undefined` makes the `Json` type pretty annoying to use, e.g. when passing values to `jsonb` columns/params.

fix: make `Json` object values possibly `undefined`

---

src/lib/PostgresMetaColumnPrivileges.ts
src/lib/PostgresMetaTablePrivileges.ts
test/server/column-privileges.ts
test/server/table-privileges.ts

`::regclass` already escapes identifier names, no need to `%I` it. E.g. `auth.users` would be double-escaped into `"auth.users"` instead of `"auth"."users"`

fix: identifier double escaping

---

src/lib/sql/columns.sql
test/lib/columns.ts

Bug fix
Having multiple checks on a column results in `/columns` returning duplicate columns: https://github.com/supabase/supabase/issues/13970
Only select one column check

fix: duplicate columns on cols w/ multiple checks

---

src/lib/types.ts
src/server/routes/columns.ts

This PR adds types definitions to the Open API spec for the column CRUD endpoints.
Currently, the Open API spec doesn't contain the expected types for payloads and responses for column endpoints.
`npm run docs: export` now creates openapi.json which contains all type definitions for payloads and responses of column endpoints.
**Impacted endpoints:**
```
- GET /columns
- POST /columns
- GET /columns/{tableId}{ordinalPosition}
- PATCH /columns/{id}
- DELETE /columns/{id}
```
I was using these endpoints and wanted to generate a client using `openapi-generator-cli` and found that types are not hooked up for these endpoints. I took inspiration from the table endpoints and hooked it up like that. I am a newbie in open-source dev and would love any sort of feedback to improve.

feat: add type def to docs for column endpoints

---

.github/workflows/ci.yml
.github/workflows/docs.yml
.github/workflows/publish-deps.yml
.github/workflows/release.yml
Dockerfile
package-lock.json
package.json

Node 16 has been EOL'd as of 2023-09-11

feat: bump node to 18

---

src/lib/db.ts
src/server/constants.ts
test/server/ssl.ts

Set the root cert directly via env instead of setting the path of the cert. Also, `PG_META_DB_SSL_ROOT_CERT` will be applied on all pg connections, instead of the user having to set `&sslrootcert=` path in the connection string.
Follow up to https://github.com/supabase/postgres-meta/pull/600

feat: allow setting ssl root cert directly

---

package-lock.json
package.json
src/lib/db.ts
src/lib/types.ts
test/lib/query.ts

feature
Error only shows the `message` w/o additional context (hints, line no., etc.)
Include other fields returned by node-postgres. Example:
```js
"error": {
"code": "42P01",
"column": undefined,
"constraint": undefined,
"dataType": undefined,
"detail": undefined,
"file": "tablecmds.c",
"formattedError": "ERROR:  42P01: table "missing_table" does not exist
",
"hint": undefined,
"internalPosition": undefined,
"internalQuery": undefined,
"length": 108,
"line": "1259",
"message": "table "missing_table" does not exist",
"name": "error",
"position": undefined,
"routine": "DropErrorMsgNonExistent",
"schema": undefined,
"severity": "ERROR",
"table": undefined,
"where": undefined,
},
```
`formattedError` follows the format in psql.

feat: add extra error fields

---

src/server/templates/typescript.ts
test/db/00-init.sql
test/server/column-privileges.ts
test/server/typegen.ts

Bug fix
Function variants aren't sorted by args & return type https://github.com/supabase/cli/issues/1165
Sort 'em

fix(typegen): sort polymorphic function variants

---

src/server/templates/typescript.ts
test/db/00-init.sql
test/server/typegen.ts

Bug fix
Generated relationships with the same `foreignKeyName` aren't sorted by `referencedRelation`
Sort by `(foreignKeyName, referencedRelation)`
https://github.com/supabase/cli/issues/1165

fix(typegen): sort relationships by (fkey name, referenced table)

---

src/server/templates/typescript.ts

bug fix
the return type `integer` of a function is `unknown`
`integer` is correctly parsed as `number`

fix: add integer to the list of numeric types

---

src/server/templates/typescript.ts
test/server/typegen.ts

Add Table and Enum helper types to TypeScript typegen.

feat: add Table and Enum helper types to typegen.

---

src/server/templates/typescript.ts
test/server/typegen.ts

Minor change
Currently, the TypeScript type generation exports the `Database` type as an `interface`. However, this is somewhat problematic in that TypeScript `interface`s don't implicitly define an index signature for their keys.
Consider the following example:
```ts
type Pokemon = {
name: string
type: string | [string, string]
}
type Pokedex = Record<string, Pokemon>
interface MyPokedex {  // Note: interface!
bulbasaur: Pokemon
charmander: Pokemon
squirtle: Pokemon
}
function getPokemon<T extends Pokedex>(pokedex: T): (keyof T)[] {
return Object.keys(pokedex)
}
```
I would expect to be able to call `getPokemon` with `MyPokedex` as the type parameter. However, this results in a type error:
```text
Type 'MyPokedex' does not satisfy the constraint 'Pokedex'.
Index signature for type …
```

change(typegen: TS): Export type, not interface

---

Dockerfile

Bug fix https://github.com/supabase/postgres-meta/issues/719
When using `sslmode=prefer` on a database that enforces ssl, node-postgres throws an error about self-signed certificate.
```
$ supabase gen types typescript --db-url 'postgres://aws-0-ap-southeast-1.pooler.supabase.com:5432/postgres'
Connecting to aws-0-ap-southeast-1.pooler.supabase.com
(node:1) ExperimentalWarning: Import assertions are not a stable feature of the JavaScript language. Avoid relying on their current behavior and syntax as those might change in a future version of Node.js.
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
file:///usr/src/app/dist/server/server.js:57
throw new …
```

fix: add ca-certificates to docker image

---

src/server/templates/typescript.ts
test/server/typegen.ts

supersedes https://github.com/supabase/postgres-meta/pull/717
If public schema is not requested, the generated type fails to compile.
When `public` schema is not requested, `Tables<'name'>` is now typed as `unknown`.
To use any non-public schema, pass in explicitly to `Tables<{ schema: 'private' }, 'name'>`.

fix(typegen): handle missing public schema

---

src/server/templates/typescript.ts
test/db/00-init.sql
test/server/typegen.ts

Bug fix https://github.com/supabase/postgres-meta/issues/726
Generating types for `create table empty()` should not crash.

fix(typegen): handle tables without any columns

---

Dockerfile
package-lock.json
package.json
src/server/server.ts

Bug fix https://github.com/supabase/postgres-meta/issues/663
Uses [closes-with-grace](https://www.npmjs.com/package/close-with-grace?activeTab=readme#usage) package from fastify authors. Shuts down the server on the following events
- process.once('SIGTERM')
- process.once('SIGINT')
- process.once('uncaughtException')
- process.once('unhandledRejection')
Tested with `docker-compose.yml`
```bash
$ docker compose up --build
...
[+] Running 1/1
✔ Container postgres-meta-meta-1  Recreated                                           0.1s 
Attaching to postgres-meta-meta-1
postgres-meta-meta-1  | (node:1) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
postgres-meta-meta-1  | (Use `node --trace-warnings ...` to show where the warning was …
```

feat: implement graceful shutdown on sigterm

---

.github/workflows/release.yml

We keep getting this error from semantic-release:
HttpError: You have exceeded a secondary rate limit. Please wait a few minutes before you try again.
This is supposedly fixed in https://github.com/semantic-release/github/pull/487.

fix(ci): flaky release

---

src/lib/sql/triggers.sql
test/lib/triggers.ts

fix: triggers w/ the same name on different schemas are duplicated [GEN-8547]

---

src/server/constants.ts
test/server/query.ts

Bug fix
Testing locally, `select pg_sleep(<forever>)` just hangs even past the `connectionTimeoutMillis`
Use `query_timeout` instead which returns `Query read timeout` with a 400

fix: query timeout

---

src/server/server.ts

Regression from https://github.com/supabase/postgres-meta/pull/687 - we shouldn't start the server when generating types/docs

fix: regression

---

src/server/templates/go.ts

Bug fix
Filter out those tables and views which don't belong to the specified schema.

fix: filter go types by the requested schema

---

src/server/server.ts

feature
Support typegen from cli mode so that scripts in [package.json](https://github.com/supabase/postgres-meta/blob/master/package.json#L26) continue to work.

fix: support gen types from command line

---

src/server/templates/typescript.ts

PostgREST doesn't detect relationships across schemas

fix(typegen): don't generate relationships across schemas

---

package.json
src/lib/sql/triggers.sql
test/db/docker-compose.yml
test/lib/triggers.ts

- Bug fix triggers listing when triggers declared over capitalized schema name
- Refactor the waiting for the test database to be ready from a `sleep 5` to a more reliable healthcheck + `--wait` docker option.

fix(triggers): list capitalized schema

---

src/server/admin-app.ts
src/server/server.ts

Currently when the main `app` is closed, or any node.js termination signal is sent (which is hijacked by `closeWithGrace` https://github.com/mcollina/close-with-grace?tab=readme-ov-file#api), an `adminApp` instance will keep it hostage and won't allow ec2 to restart everything correctly.
This can be tested by updating `/health` endpoint to call `app.close()` and observing that process is still running due to `adminApp` server being bound.
This will hopefully kill server instantly and won't let other requests come in to this instance as observed in our ec2 logs now.
Sidenote: why do we expose prometheus metrics on a separate port/app and not just `/metrics` endpoint within same app instead? @soedirgo

fix: Close both apps to allow for process restart

---

src/server/constants.ts
src/server/templates/typescript.ts
test/server/typegen.ts

This PR fixes the incorrect default alias generation for TypeScript type schemas when using a single non‑public schema with `supabase gen types`.
Currently, the TypeScript template always hardcodes the default schema alias as:
```ts
export type PublicSchema = Database[Extract<keyof Database, "public">]
```
This means that when a user generates types using a non‑public schema (for example, `--schema robo`), the generated helper types (for example. `Tables<"test_table">`) incorrectly reference the public schema, even if no tables exist there.
Relevant issues: 
- cli:  [#3146](https://github.com/supabase/cli/issues/3146), [#3061](https://github.com/supabase/cli/issues/3061)
- postgres-meta: #833 (for additional context)
This PR updates the TypeScript template in pg‑meta so that when exactly …

fix(template): dynamically set default schema alias in typescript type generation

---

src/server/templates/typescript.ts
test/server/typegen.ts

Extends typescript schema generation to provide access to constants representing enum values.
Resolves #832
Resolves #864 
Generated schema provides type data for database enums.
Generated schema provides type data and constant values for database enums.

Add constant arrays of enum values for typescript

---

src/server/templates/typescript.ts
test/db/00-init.sql
test/server/typegen.ts

- A function definition in postgresql can be declared multiples times with differents arguments. But it's return type must be the same across all definition. Therefore, the generated types should match that. This turn multiples definitions like so:
```ts
get_todos_setof_rows: { Args: { ... }, Returns: { ... }  } | { Args: { ... }, Returns: { ... }  }
```
Into the more correct:
```ts
get_todos_setof_rows: { Args: { ... } | { ... }, Returns: { ... }  }
```
This also will fix on the type inference side the return type for `rpc` functions calls from an union of object, to a single object.

fix(typescript): function only have union over args

---

package.json
src/server/constants.ts

- Make the variable autodescriptive and the unit more easy to reason with Following comment from: https://github.com/supabase/infrastructure/pull/22299\#discussion_r2021926148
Bug fix, feature, docs update, ...

fix: rename max_result variable default to MB

---

src/server/constants.ts
src/server/utils.ts

Cleanly kill long running queries before envoy timeout the request if possible. 
Be deployed with: https://github.com/supabase/supabase/pull/34865
For the frontend side, and have a clear CTA inviting the user to use a direct database connection (maybe this could be part of the error message on postgres-meta side as well, open to suggestions here).

fix: add a maximum query time limit

---

.github/workflows/release.yml

Docker release action seems to consistenly fail because of some caching issue.

fix: remove cache in release action

---

src/server/server.ts

So we can understand better what cause the ending of the container

fix: add more logs to the exit path

---

src/server/templates/typescript.ts
test/server/typegen.ts

Should resolve: https://github.com/supabase/postgres-meta/issues/929

fix(typegen): use javascript deterministic sort for args join

---

src/server/routes/index.ts
test/server/ssl.ts

- Catch if there is an invalid pg url early on in the request processing and unify the error message
Related: PGMETA-53

fix: catch invalid url early

---

package-lock.json
package.json
src/lib/PostgresMeta.ts
src/lib/db.ts
src/server/admin-app.ts
src/server/app.ts
src/server/routes/query.ts
src/server/sentry.ts
src/server/server.ts

For better performances tracing and error alerting use sentry
Closes: PGMETA-54

fix(monitoring): add sentry monitoring

---

src/server/routes/column-privileges.ts
src/server/routes/columns.ts
src/server/routes/config.ts
src/server/routes/extensions.ts
src/server/routes/foreign-tables.ts
src/server/routes/functions.ts
src/server/routes/generators/go.ts
src/server/routes/generators/swift.ts
src/server/routes/generators/typescript.ts
src/server/routes/indexes.ts
src/server/routes/materialized-views.ts
src/server/routes/policies.ts
src/server/routes/publications.ts
src/server/routes/query.ts
src/server/routes/roles.ts
src/server/routes/schemas.ts
src/server/routes/table-privileges.ts
src/server/routes/tables.ts
src/server/routes/triggers.ts
src/server/routes/types.ts
src/server/routes/views.ts
src/server/utils.ts
test/server/query.ts

feature
`application_name` setting is always set as `postgres-meta <ver>`
`application_name` can be customized by passing a `x-pg-application-name` header. This allows distinguishing internal queries (e.g. user queries from SQL editor vs. internal queries on table editor vs. queries from user's own conns) which affords us better query analysis (e.g. excluding queries from table editor when displaying long running queries)

feat: allow setting application_name via header

---

src/server/templates/typescript.ts

Bug fix
If multiple schemas have enum types with the same name, the generated enum types all use the same schema, which is the first schema returned by pgMeta.types.list().
```typescript
export type Database = {
schema_1: {
Tables: {
table_name: {
Row: {
type: Database["schema_1"]["Enums"]["some_enum"];
};
};
};
Enums: {
some_enum: "some_value" | "some_other_value";
};
};
schema_2: {
Tables: {
table_name: {
Row: {
// schema_1 is used here
type: Database["schema_1"]["Enums"]["some_enum"];
};
};
};
Enums: {
some_enum: "some_value" | "some_other_value";
};
};
};
```
If the current/self schema has the enum type, generated enum type will use the current schema instead of the first schema. 
```typescript
export type Database = {
schema_1: {
Tables: {
table_name: {
Row: {
type: …
```

Prioritize current schema for pg type generation

---

.gitignore

Since sentry is configured, make sure we never accidentally commit the sentry-cli config by accident

chore: ignore sentryclirc

---

src/server/templates/swift.ts

Adds "case" to the list of Swift keywords so that a Postgres table with a column named 'case' won't cause the Swift type generation to produce invalid code.
`gen types swift` with a table that has a column named 'case' will produce the following code:
```swift
public let case: String        // ERROR: Keyword 'case' cannot be used as an identifier here. 
// FIX: If this name is unavoidable, use backticks to escape it
```
`case` will be encoded in backticks so there will be no error:
```swift
public let `case`: String
```
--

FIX: Add 'case' to list of Swift keywords for Swift type generation

---

src/server/templates/typescript.ts
test/server/typegen.ts

- Improve typescript function args generation so it's more stable for the same function declaration
- Add a test to avoid regression, ensuring that the type generation is stable regardless of:
1. Entity order creation (eg: `CREATE TABLE A; CREATE TABLE B` or `CREATE TABLE B; CREATE TABLE A`) should always result in the same final types.
2. Entities properties order declaration (except for enums). Which wasn't the case for function args declaration (eg: `CREATE TABLE A (col1, col2)` or `CREATE TABLE A (col2, col1)`) should always result in the same final types.
Fixes: #959

fix(typegen): improve ts typegen consistency between generation

---

src/server/templates/typescript.ts
test/server/typegen.ts

Fix spelling mistake in TypeScript generation template that was propagating to all generated database type files.
Bug fix - corrects spelling error in code generation template
The TypeScript generation template contains a spelling error where "instanciate" is used instead of the correct spelling "instantiate" in the comment:
```typescript
// Allows to automatically instanciate createClient with right options
```
This spelling error propagates to all generated `DatabaseDefinitions.ts` files for every user who runs `supabase gen types typescript`, affecting code quality and professionalism.
Please link any relevant issues here: Related to spell-checking failures in pre-commit hooks across user projects.
The comment now uses the correct spelling "instantiate":
```typescript
// Allows to …
```

fix(ts-template): correct "instanciate" to "instantiate" misspelling

---

src/server/templates/typescript.ts

- Follow up refactor isolating duplicated typescript generation logic into their own dedicated functions

chore: dedup typescript typegen logic

---

src/server/templates/typescript.ts

`unknown`  and `any` already swallow nullable type, don't need an union for it, in such case we follow tslint best practice:
https://typescript-eslint.io/rules/no-redundant-type-constituents/
Fixes:
- https://github.com/supabase/cli/issues/4234
- https://github.com/supabase/cli/issues/577

fix(typescript): union unknown null
